var phrases = [
"a good deal",
"a great deal",
"a variety of",
"above all",
"according to",
"account for",
"accustomed to",
"add up to",
"after a while",
"after all",
"ahead of",
"ahead of time",
"al all costs",
"all at once",
"all but",
"all of a sudden",
"all out",
"all round",
"all the same",
"allow for",
"and so forth",
"and yet",
"anything but",
"approve of",
"around the clock",
"arrive at",
"as a result of",
"as a rule",
"as far as",
"as for",
"as if",
"as long as",
"as regards",
"as though",
"as to",
"as usual",
"as well",
"as well as",
"as yet",
"aside from",
"ask after",
"ask for",
"at a loss",
"at a time",
"at all",
"at all events",
"at any rate",
"at best",
"at first",
"at first sight",
"at hand",
"at heart",
"at intervals",
"at large",
"at length",
"at most",
"at no time",
"at one time",
"at present",
"at stake",
"at the best",
"at the cost of",
"at the mercy of",
"at the moment",
"at the most",
"at the same time",
"at the worst",
"at times",
"at work",
"at worst",
"attached to",
"back and forth",
"back down",
"back of",
"back off",
"back up",
"based on",
"be about",
"be bound to",
"be concerned in",
"be concerned with",
"be fed up with",
"be friends with",
"be keen on",
"be short of",
"bear in mind",
"break away",
"break away from",
"break down",
"break in",
"break into",
"break off",
"break out",
"break through",
"break up",
"bring about",
"bring down",
"bring forth",
"bring forward",
"bring into effect",
"bring into operation",
"bring into practice",
"bring out",
"bring to",
"bring up",
"build up",
"burn out",
"burn up",
"but for",
"by accident",
"by and by",
"by chance",
"by chance",
"by comparison in comparison with",
"by far",
"by hand",
"by heart",
"by itself",
"by oneself",
"by the reason of",
"by the way",
"by turns",
"by virtue of",
"by way of",
"call for",
"call forth",
"call off",
"call on",
"call out",
"call up",
"call upon",
"care about",
"care for",
"care nothing about",
"carry into effect",
"carry into practice",
"carry off",
"carry on",
"carry out",
"cast light on",
"cast light upon",
"catch at",
"catch at",
"catch fire",
"catch on",
"catch on",
"catch one's breath",
"catch one's eye",
"catch sight of",
"catch up with",
"catch up with",
"cave in",
"cave in",
"check in",
"check on",
"check out",
"check up",
"check up on",
"cheer up",
"clear away",
"clear up",
"come around",
"come into effect",
"come into force",
"come into operation",
"come off",
"come on",
"come out",
"come round",
"come through",
"come to",
"come to the point",
"come true",
"come up",
"come up again",
"come up to",
"come up with",
"compare to",
"count on",
"count up",
"cover up",
"cross out",
"cut across",
"cut back",
"cut down",
"cut in",
"cut off",
"cut out",
"cut short",
"cut short",
"deal with",
"derive from",
"die down",
"die out",
"do away with",
"do one's best",
"do without",
"double up",
"draw in",
"draw up",
"dress up",
"drop in",
"drop by",
"drop off",
"drop out",
"drop over",
"due to",
"dwell on",
"enjoy oneself",
"even if",
"even now",
"even then",
"even though",
"ever so",
"every now and then",
"every other",
"face to face",
"face up to",
"fall back on",
"fall behind",
"fall in with sb",
"fall in with sth",
"fall out",
"fall through",
"far from",
"feed in",
"feed on",
"feel like",
"figure out",
"find fault",
"find out",
"flare up",
"for a while",
"for good",
"for long",
"for one thing",
"for purpose of",
"for short",
"for the better",
"for the moment",
"for the present",
"for the purpose of",
"for the sake of",
"for the time being",
"from time to time",
"gain an advantage",
"get across",
"get along with",
"get around",
"get around",
"get at",
"get away",
"get by",
"get by heart",
"get down",
"get down to",
"get hold of",
"get in",
"get into",
"get off",
"get on with",
"get out of",
"get over",
"get round",
"get round to",
"get the best of",
"get the better of",
"get the better of",
"get through",
"get together",
"get together with sb",
"get up",
"give away",
"give back",
"give in",
"give off",
"give oneself away",
"give oneself up",
"give out",
"give rise to",
"give up",
"give way",
"give way to",
"go after",
"go ahead",
"go along with",
"go around",
"go back on",
"go by",
"go down",
"go for",
"go in for",
"go into",
"go into effect",
"go into force",
"go into operation",
"go off",
"go on",
"go on the stage",
"go out",
"go out",
"go over",
"go round",
"go through",
"go under",
"go up",
"go with",
"go without",
"go wrong",
"good for",
"had better",
"hand down",
"hand in",
"hand in hand",
"hand on",
"hand out",
"hand over",
"hang about",
"hang back",
"hang on",
"hang on to",
"hang onto",
"hang up",
"happen to",
"hardly any",
"hardly before",
"hardly when",
"have an advantage",
"have in mind",
"have nothing to do with",
"have on",
"have something to do with",
"have sth back",
"have to do with",
"head for",
"head on",
"heart and soul",
"help oneself",
"here and there",
"hold back",
"hold on",
"hold onto",
"hold out",
"hold pace with",
"hold up",
"hurry up",
"improve on",
"improve upon",
"in a hurry",
"in a moment",
"in a sense",
"in a way",
"in a word",
"in accordance with",
"in addition to",
"in advance",
"in all",
"in all truth",
"in any case",
"in any case",
"in any event",
"in brief",
"in bulk",
"in case",
"in case of",
"in charge",
"in charge",
"in charge of",
"in charge of",
"in common",
"in conclusion",
"in connection to",
"in connection with",
"in consequence",
"in consequence of",
"in contrast to",
"in contrast with",
"in danger",
"in debt",
"in detail",
"in difficulties",
"in effect",
"in essence",
"in excess of",
"in fact",
"in favor of",
"in force",
"in future",
"in half",
"in hand",
"in honor of",
"in itself",
"in line",
"in line with",
"in memory of",
"in nature",
"in no case",
"in no case",
"in no time",
"in no way",
"in of place",
"in of sight",
"in one's way",
"in other words",
"in particular",
"in person",
"in place of",
"in practice",
"in proportion",
"in proportion to",
"in public",
"in question",
"in regard to",
"in relation to",
"in secret",
"in sequence",
"in short",
"in step",
"in stock",
"in sum",
"in tears",
"in terms of",
"in the air",
"in the course of",
"in the end",
"in the event of",
"in the face of",
"in the first place",
"in the future",
"in the last place",
"in the least",
"in the light of",
"in the long run",
"in the past",
"in the shape of",
"in the way",
"in the way of",
"in the world",
"in truth",
"in turn",
"in vain",
"keep an eye on",
"keep away",
"keep away from sth",
"keep back",
"keep company with",
"keep down",
"keep from",
"keep house",
"keep in",
"keep in mind",
"keep in touch",
"keep in with",
"keep off",
"keep on",
"keep on doing sth",
"keep one's head",
"keep one's word",
"keep out of",
"keep pace with",
"keep to",
"keep track",
"keep up",
"keep up with",
"knock down",
"knock out",
"lay aside",
"lay down",
"lay off",
"lay out",
"lead the way",
"learn by heart",
"leave alone",
"leave behind",
"leave out",
"lend itself to",
"let alone",
"let down",
"let go",
"let go of",
"let in",
"let into",
"let loose",
"let off",
"let out",
"lie in",
"line up",
"little by little",
"live by",
"live on",
"live through",
"live up to",
"look after",
"look at",
"look back",
"look down on",
"look down upon",
"look for",
"look forward to",
"look in",
"look into",
"look on",
"look out",
"look over",
"look through",
"look up",
"look up to",
"lose heart",
"lose one's head",
"lose one's temper",
"lose track",
"make a difference",
"make a face",
"make believe",
"make for",
"make friends",
"make fun of",
"make one's way",
"make out",
"make sense",
"make the best of",
"make the difference",
"make the most of",
"make up",
"make up for",
"make up one's mind",
"make use of",
"make way",
"matter of fact",
"mix up",
"next door",
"no doubt",
"no wonder",
"nothing but",
"now and then",
"now that",
"occur to",
"of course",
"off and on",
"off duty",
"on a large scale",
"on a small scale",
"on account of",
"on an average",
"on average",
"on behalf of",
"on board",
"on business",
"on condition that",
"on duty",
"on end",
"on fire",
"on guard",
"on hand",
"on occasion",
"on occasions",
"on one hand",
"on one's honor",
"on one's own",
"on other hand",
"on purpose",
"on sale",
"on schedule",
"on second thoughts",
"on the average",
"on the basis of",
"on the contrary",
"on the one hand",
"on the other hand",
"on the point of",
"on the road",
"on the side",
"on the sly",
"on the spot",
"on the stage",
"on the whole",
"on top of",
"once and for all",
"once for all",
"once in a while",
"once more",
"one after another",
"one another",
"or else",
"or so",
"out of breath",
"out of control",
"out of danger",
"out of date",
"out of doors",
"out of order",
"out of place",
"out of practice",
"out of sight",
"out of step",
"out of touch",
"out of work",
"over and over",
"over and over again",
"pass away",
"pass off",
"pass out",
"pay attention to",
"pay back",
"pay off",
"pay up",
"per cent",
"per cent",
"Phrases",
"Phrases",
"Phrases",
"Phrases",
"Phrases",
"pick out",
"pick up",
"play a part",
"play a part in",
"play with",
"point out",
"pull down",
"pull in",
"pull off",
"pull on",
"pull out",
"pull up",
"put over",
"put across",
"put aside",
"put away",
"put down",
"put forward",
"put in",
"put in for",
"put in order",
"put into effect",
"put into operation",
"put off",
"put on",
"put out",
"put to use",
"put up",
"put up with",
"right away",
"ring off",
"round the clock",
"rub out",
"run away with",
"run down",
"run for",
"run into",
"run off",
"run out of",
"run over",
"run short",
"run through",
"scrape through",
"see off",
"see through",
"see to",
"send for",
"send in",
"send off",
"serve right",
"set about +doing",
"set aside",
"set back",
"set down",
"set fire to",
"set forth",
"set free",
"set off",
"set out",
"set out to",
"set up",
"settle down",
"show in",
"show off",
"show up",
"shut off",
"shut out",
"sick of",
"side by side",
"side walk",
"sit for",
"sit in",
"sit up",
"so far",
"so far as",
"so far as be concerned",
"stand by",
"stand for",
"stand out",
"stand up",
"stand up for",
"stand up to",
"start from scratch",
"step in",
"step up",
"stick out",
"stick to",
"sum up",
"take a chance",
"take a chance",
"take a delight in",
"take advantage of",
"take after",
"take as",
"take away",
"take care",
"take care of",
"take charge of",
"take charge of",
"take delight in",
"take down",
"take effect",
"take for",
"take in",
"take into account",
"take off",
"take on",
"take one's time",
"take over",
"take pains",
"take the place of",
"take to",
"take turns",
"take up",
"talk back",
"talk into",
"thanks to",
"the moment",
"the moment that",
"think better of",
"think of",
"think of as",
"think over",
"throw away",
"throw light on",
"throw light upon",
"to begin with",
"to the point",
"touch on",
"touch up",
"try on",
"try one's best",
"try out",
"tune in",
"tune into",
"turn away",
"turn down",
"turn in",
"turn into",
"turn off",
"turn on",
"turn out",
"turn over",
"turn to",
"turn up",
"under control",
"up to",
"up to date",
"use up",
"warm up",
"wear off",
"wear out",
"what about",
"what if",
"whether or",
"while away",
"wipe out",
"with regard to",
"with relation to",
"with respect to",
"with the purpose of",
"word for word",
"work out",
"work up",
"write off"
];
